services:
  api:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: $DB__USER
      POSTGRES_PASSWORD: $DB__PASSWORD
      POSTGRES_DB: $DB__DATABASE
      DB__PORT: $DB__PORT
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    env_file:
      - ./.env
networks:
  api-network:
    driver: bridge